[package]
name = "ashtlog"
version = "0.2.0"
authors = ["ashtneoi <ashtneoi@gmail.com>"]
edition = "2018"
description = "A hierarchical logging system"
repository = "https://github.com/ashtneoi/ashtlog"
license = "MIT"
